version: '3.1'

services:
    db:
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: qwe123

    adminer:
        image: adminer
        depends_on:
            - db
        restart: always
        ports:
            - 8080:8080

    redis:
        image: redis:4.0.14
        ports:
            - 6379:6379
        volumes:
            - ./cache:/data
